
parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: ovt_db
    database_user: root
    database_password: toor
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 57d04d116f6afea649063287b7fb78208ea0d887
    transcripting_server: http://localhost:9090
    signaling_server: http://localhost:8880/