
parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: ovt_db
    database_user: root
    database_password: toor
    mailer_transport: smtp
    mailer_host: mailhost.rd.francetelecom.fr
    mailer_port: 2525
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 57d04d116f6afea649063287b7fb78208ea0d887
    transcripting_server: http://vepi-ovt.epi.orange-labs.fr:5065
    signaling_server: http://vepi-ovt.epi.orange-labs.fr:5066/
    app_name: OVT 3.1