security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CLIENT:            ROLE_USER
        ROLE_COM_CLIENT:         ROLE_CLIENT
        ROLE_WORKER:            ROLE_USER
        ROLE_PROVIDER_ADMIN:    ROLE_WORKER
        ROLE_ACCOUNTING:        ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_COM_ADMIN, ROLE_PROVIDER_ADMIN, ROLE_ACCOUNTING,  ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username


    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider                
                always_use_default_target_path : true
                default_target_path: /profilRedirection
                use_referer : true
            logout:
                path:   /logout
                target: /login
            anonymous:    true

    access_control: 
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/adminclient, role:   ROLE_COM_CLIENT}
        - { path: ^/client/adminclient/session/, role: ROLE_CLIENT  }
        - { path: ^/client, role: ROLE_CLIENT }
        - { path: ^/provider/, role: ROLE_WORKER }
        - { path: ^/accounting/, role: ROLE_ACCOUNTING }
        - { path: ^/provider/adminprovider/, role: ROLE_PROVIDER_ADMIN }
        - { path: ^/superadmin, role: ROLE_SUPER_ADMIN }