ovt_front_end_provider_homepage:
    path:     /
    defaults: { _controller: OVTFrontEndProviderBundle:Default:index }

ovt_front_end_admin_provider_homepage:
    path:     /admin
    defaults: { _controller: OVTFrontEndProviderBundle:Default:index }
