ovt_front_end_provider_homepage:
    path:     /
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:index }

ovt_front_end_provider_my_sessions:
    path:     /mysessions
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:mySessions }
    options:
        expose: true

ovt_front_end_provider_calendar:
    path:     /calendar/{idWorker}
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:calendarView, idWorker:-1, coreCalendar:-1 }

ovt_front_end_provider_archives:
    path:     /archives
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:archivesView }

ovt_front_end_provider_retrieve_affected_sessions_to_worker:
    path: /myaffectedsessions/{idWorker}
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:retrieveAffectedSessions}
    options:
        expose: true
    requirements:
        _method: GET

ovt_front_end_provider_profile:
    path: /profile/view
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:profileView }
    requirements:
        _method:  GET







ovt_front_end_admin_provider_homepage:
    path:     /adminprovider
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:index }

ovt_front_end_admin_provider_set_sessions:
    path:     /adminprovider/setsession
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:setSessions }
    options:
        expose: true

ovt_front_end_admin_provider_worker:
    path:     /adminprovider/worker
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:worker }
    options:
        expose: true

ovt_front_end_admin_provider_group:
    path:     /adminprovider/group
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:group }
    options:
        expose: true


ovt_front_end_admin_provider_new_worker:
    path: /adminprovider/new/worker
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:addNewWorker }
    options:
        expose: true

ovt_front_end_admin_provider_new_group:
    path: /adminprovider/new/group
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:addNewGroup }
    options:
        expose: true
    requirements:
        _method:  POST

ovt_front_end_admin_provider_get_json_groups_by_admin:
    path: /adminprovider/groups/json
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:renderJSONProviderGroups }
    options:
        expose: true

ovt_front_end_admin_provider_get_services_json:
    path: /adminprovider/services/json
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:getAllServicesJSON }
    options:
        expose: true

ovt_front_end_admin_provider_get_group_by_id:
    path: /adminprovider/group/{id}
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:getGroupById }
    options:
        expose: true

ovt_front_end_admin_provider_get_session_by_id:
    path: /adminprovider/session/{id}
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:getSessionById}
    options:
        expose: true

ovt_front_end_admin_provider_get_worker_by_id:
    path: /adminprovider/worker/{id}
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:getWorkerById}
    options:
        expose: true

ovt_front_end_admin_provider_delete_worker_by_id:
    path: /adminprovider/delete/worker
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:deleteWorkerById}
    options:
        expose: true
    requirements:
        _method: POST

ovt_front_end_admin_provider_delete_group_by_id:
    path: /adminprovider/delete/group
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:deleteGroupById}
    options:
        expose: true
    requirements:
        _method: POST

ovt_front_end_admin_provider_set_worker_group:
    path: /adminprovider/setgroup/worker
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:setGroupWorker}
    options:
        expose: true
    requirements:
        _method: POST

ovt_front_end_admin_provider_set_worker_to_session:
    path: /adminprovider/affect/worker/session
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:affectWorkerToSession}
    options:
        expose: true
    requirements:
        _method: POST

ovt_front_end_admin_provider_update_session:
    path: /adminprovider/update/session
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:updateSession}
    options:
        expose: true
    requirements:
        _method: POST

ovt_front_end_admin_provider_update_group:
    path: /adminprovider/update/group
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:updateGroup}
    options:
        expose: true
    requirements:
        _method: POST

ovt_front_end_admin_provider_update_worker:
    path: /adminprovider/update/worker
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:updateWorker}
    options:
        expose: true
    requirements:
        _method: POST

ovt_front_end_admin_provider_action_session:
    path: /adminprovider/{action}/session
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:updateStateSession}
    options:
        expose: true
    requirements:
        _method: POST

ovt_front_end_admin_provider_worker_calendar:
    path: /adminprovider/calendar/{idWorker}/{coreCalendar}
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:calendarView, idWorker:-1, coreCalendar:-1 }
    options:
        expose: true


ovt_front_end_provider_admin_retrieve_affected_sessions_to_worker:
    path: /adminprovider/worker/affectedSessions/{id}
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:workerAffectedSessions}
    options:
        expose: true
    requirements:
        _method: GET






test:
    path:     /testpro
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:test }
testFeed:
    path:     /test/feed
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:JSONFeed }
    options:
        expose: true