ovt_front_end_provider_homepage:
    path:     /
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:index }

ovt_front_end_provider_my_sessions:
    path:     /mysessions
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:mySessions }

ovt_front_end_provider_calendar:
    path:     /calendar
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:calendarView }

ovt_front_end_provider_archives:
    path:     /archives
    defaults: { _controller: OVTFrontEndProviderBundle:Provider:archivesView }


ovt_front_end_admin_provider_homepage:
    path:     /adminprovider
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:index }

ovt_front_end_admin_provider_set_sessions:
    path:     /adminprovider/setsession
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:setSessions }
    options:
        expose: true

ovt_front_end_admin_provider_worker:
    path:     /adminprovider/worker
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:worker }

ovt_front_end_admin_provider_group:
    path:     /adminprovider/group
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:group }

ovt_front_end_admin_provider_profile:
    path: /adminprovider/profile/view
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:profileView }
    requirements:
        _method:  GET

ovt_front_end_admin_provider_new_worker:
    path: /adminprovider/new/worker
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:addNewWorker }
    options:
        expose: true
        
ovt_front_end_admin_provider_get_session_by_id:
    path: /adminprovider/session/{id}
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:getSessionById}
    options:
        expose: true

ovt_front_end_admin_provider_get_worker_by_id:
    path: /adminprovider/worker/{id}
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:getWorkerById}
    options:
        expose: true


ovt_front_end_admin_provider_set_worker_to_session:
    path: /adminprovider/affect/worker/session
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:affectWorkerToSession}
    options:
        expose: true
    requirements:
        _method: POST

ovt_front_end_admin_provider_update_session:
    path: /adminprovider/update/session
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:updateSession}
    options:
        expose: true
    requirements:
        _method: POST

ovt_front_end_admin_provider_update_worker:
    path: /adminprovider/update/worker
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:updateWorker}
    options:
        expose: true
    requirements:
        _method: POST

ovt_front_end_admin_provider_action_session:
    path: /adminprovider/{action}/session
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:updateStateSession}
    options:
        expose: true
    requirements:
        _method: POST



test:
    path:     /testpro
    defaults: { _controller: OVTFrontEndProviderBundle:ProviderAdmin:test }