ovt_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: OVTUserBundle:Default:index }

ovt_user_profil_rediction:
    path:     /profilRedirection
    defaults: { _controller: OVTUserBundle:UserInfos:profilRedirection }

ovt_user_profil_update:
    path:     /profile/update
    defaults: { _controller: OVTUserBundle:UserInfos:updateProfile }
    requirements:
        _method: POST

ovt_user_password_update:
    path:     /password/update
    defaults: { _controller: OVTUserBundle:UserInfos:updatePassword }
    requirements:
        _method: POST