ovt_front_end_client_homepage:
    path:     /
    defaults: { _controller: OVTFrontEndClientBundle:FrontClient:index }

ovt_front_end_admin_client_homepage:
    path:     /admin
    defaults: { _controller: OVTFrontEndClientBundle:FrontClient:index }
