ovt_back_end_admin_homepage:
    path:     /
    defaults: { _controller: OVTBackEndAdminBundle:SuperAdmin:index }

ovt_back_end_admin_gestion:
    path:     /gestion/{gestion}
    defaults: { _controller: OVTBackEndAdminBundle:SuperAdmin:gestion, gestion:'user' }
    requirements:
        gestion: adminClient|adminProvider|client|provider|service
    options:
        expose: true

ovt_back_end_admin_gestion_new:
    path:     /gestion/{gestion}/addnew
    defaults: { _controller: OVTBackEndAdminBundle:SuperAdmin:addNew, gestion:'user' }
    requirements:
        gestion: adminClient|adminProvider|client|provider|service
        _method:  GET

ovt_back_end_admin_gestion_new_service:
    path:     /gestion/service/addnew
    defaults: { _controller: OVTBackEndAdminBundle:ServiceAdmin:addNew }
    requirements:
        _method:  POST

ovt_back_end_admin_gestion_get_service_by_id:
    path:     /gestion/service/{id}
    defaults: { _controller: OVTBackEndAdminBundle:ServiceAdmin:getServiceById }
    requirements:
        id:  \d+

ovt_back_end_admin_gestion_get_organisation_by_id:
    path:     /gestion/{organisation}/{id}
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:getOrgById }
    requirements:
        id:  \d+
    options:
        expose: true


ovt_back_end_admin_gestion_new_user:
    path:     /gestion/user/addnew
    defaults: { _controller: OVTBackEndAdminBundle:UserAdmin:addNew }
    requirements:
        _method:  POST






ovt_back_end_admin_admin_update_service:
    path:     /update/service
    defaults: { _controller: OVTBackEndAdminBundle:ServiceAdmin:update }
    requirements:
        _method:  POST

ovt_back_end_admin_delete_service_by_id:
    path:     /delete/service
    defaults: { _controller: OVTBackEndAdminBundle:ServiceAdmin:delete }
    requirements:
        _method:  POST
    options:
        expose: true


ovt_back_end_admin_org_services_choice:
    path: /services/choice/{idOrg}
    defaults: { _controller: OVTBackEndAdminBundle:ServiceAdmin:servicesChoice}
    options:
        expose: true
    requirements:
        _method: GET

ovt_back_end_admin_org_service_toggle:
    path: /services/choice/{idOrg}/{idService}
    defaults: { _controller: OVTBackEndAdminBundle:ServiceAdmin:serviceToggle}
    options:
        expose: true
    requirements:
        _method: GET






ovt_back_end_admin_gestion_new_organisation:
    path:     /gestion/{organisation}/addnew
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:addNewOrg }
    requirements:
        _method:  POST


ovt_back_end_admin_gestion_organisation_setadmin:
    path: /gestion/{org}/setadmin
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:setAdmin }
    requirements:
        _method:  POST
    options:
        expose: true

ovt_back_end_admin_gestion_organisation_update_post:
    path: /gestion/{org}/update
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:updatePost }
    options:
        expose: true
    requirements:
        _method:  POST

ovt_back_end_admin_gestion_organisation_deleteadmin:
    path: /gestion/{org}/deleteadmin/{idOrg}/{idAdmin}
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:deleteAdmin }
    requirements:
        _method:  GET
    options:
        expose: true

ovt_back_end_admin_gestion_organisation_delete:
    path: /gestion/{org}/delete
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:deleteOrg }
    requirements:
        _method:  POST
    options:
        expose: true

ovt_back_end_admin_gestion_organisation_restore:
    path: /gestion/{org}/restore
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:restoreOrg }
    requirements:
        _method:  POST
    options:
        expose: true


ovt_back_end_admin_manage_service:
    path: /{organisation}/manage/service/{idOrg}
    defaults: { _controller: OVTBackEndAdminBundle:OrgServiceAdmin:manageServices }
    requirements:
        organisation: client|provider
    options:
        expose: true

ovt_back_end_admin_profile:
    path: /profile/view
    defaults: { _controller: OVTBackEndAdminBundle:ProfileAdmin:view }
    requirements:
        _method:  GET