ovt_back_end_admin_homepage:
    path:     /
    defaults: { _controller: OVTBackEndAdminBundle:SuperAdmin:index }

ovt_back_end_admin_gestion:
    path:     /gestion/{gestion}
    defaults: { _controller: OVTBackEndAdminBundle:SuperAdmin:gestion, gestion:'user' }
    requirements:
        gestion: user|client|provider|service
    options:
        expose: true

ovt_back_end_admin_gestion_new:
    path:     /gestion/{gestion}/addnew
    defaults: { _controller: OVTBackEndAdminBundle:SuperAdmin:addNew, gestion:'user' }
    requirements:
        gestion: user|client|provider|service
        _method:  GET

ovt_back_end_admin_gestion_new_service:
    path:     /gestion/service/addnew
    defaults: { _controller: OVTBackEndAdminBundle:ServiceAdmin:addNew }
    requirements:
        _method:  POST

ovt_back_end_admin_gestion_get_service_by_id:
    path:     /gestion/service/{id}
    defaults: { _controller: OVTBackEndAdminBundle:ServiceAdmin:getServiceById }
    requirements:
        id:  \d+
        
ovt_back_end_admin_gestion_get_organisation_by_id:
    path:     /gestion/{organisation}/{id}
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:getOrgById }
    requirements:
        id:  \d+
    options:
        expose: true
 

ovt_back_end_admin_gestion_new_user:
    path:     /gestion/user/addnew
    defaults: { _controller: OVTBackEndAdminBundle:UserAdmin:addNew }
    requirements:
        _method:  POST
        
ovt_back_end_admin_gestion_new_organisation:
    path:     /gestion/{organisation}/addnew
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:addNewOrg }
    requirements:
        _method:  POST

        
ovt_back_end_admin_gestion_organisation_setadmin:
    path: /gestion/{org}/setadmin
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:setAdmin }
    requirements:
        _method:  POST

ovt_back_end_admin_gestion_organisation_update:
    path: /gestion/{org}/update/{idOrg}
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:update }
    options:
        expose: true
    requirements:
        _method:  GET
        
ovt_back_end_admin_gestion_organisation_update_post:
    path: /gestion/{org}/update
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:updatePost }
    options:
        expose: true
    requirements:
        _method:  POST
       
ovt_back_end_admin_gestion_organisation_deleteadmin:
    path: /gestion/{org}/deleteadmin/{idOrg}/{idAdmin}
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:deleteAdmin }
    requirements:
        _method:  GET
    options:
        expose: true
        
ovt_back_end_admin_gestion_organisation_delete:
    path: /gestion/{org}/delete/{idOrg}
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:deleteOrg }
    requirements:
        _method:  GET
    options:
        expose: true
        
        
ovt_back_end_admin_profile:
    path: /profile/view
    defaults: { _controller: OVTUserBundle:Profile:view }
    requirements:
        _method:  GET