ovt_back_end_admin_homepage:
    path:     /
    defaults: { _controller: OVTBackEndAdminBundle:SuperAdmin:index }

ovt_back_end_admin_gestion:
    path:     /gestion/{gestion}
    defaults: { _controller: OVTBackEndAdminBundle:SuperAdmin:gestion, gestion:'user' }
    requirements:
        gestion: user|client|provider|service

ovt_back_end_admin_gestion_new:
    path:     /gestion/{gestion}/addnew
    defaults: { _controller: OVTBackEndAdminBundle:SuperAdmin:addNew, gestion:'user' }
    requirements:
        gestion: user|client|provider|service
        _method:  GET

ovt_back_end_admin_gestion_new_service:
    path:     /gestion/service/addnew
    defaults: { _controller: OVTBackEndAdminBundle:ServiceAdmin:addNew }
    requirements:
        _method:  POST

ovt_back_end_admin_gestion_get_service_by_id:
    path:     /gestion/service/{id}
    defaults: { _controller: OVTBackEndAdminBundle:ServiceAdmin:getServiceById }
    requirements:
        id:  \d+
ovt_back_end_admin_gestion_get_client_by_id:
    path:     /gestion/client/{id}
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:getOrgById }
    requirements:
        id:  \d+
        
ovt_back_end_admin_gestion_new_client:
    path:     /gestion/client/addnew
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:addNewClient }
    requirements:
        _method:  POST

ovt_back_end_admin_gestion_new_provider:
    path:     /gestion/provider/addnew
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:addNewProvider }
    requirements:
        _method:  POST

ovt_back_end_admin_gestion_new_user:
    path:     /gestion/user/addnew
    defaults: { _controller: OVTBackEndAdminBundle:UserAdmin:addNew }
    requirements:
        _method:  POST
        
ovt_back_end_admin_gestion_setadmin:
    path: /gestion/{gestion}/setadmin
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:setAdmin }
    requirements:
        gestion: user|client|provider|service
        _method:  POST

ovt_back_end_admin_gestion_update:
    path: /gestion/{gestion}/update
    defaults: { _controller: OVTBackEndAdminBundle:OrganisationAdmin:Update }
    requirements:
        gestion: user|client|provider|service
        _method:  POST