ovt_back_end_admin_homepage:
    path:     /
    defaults: { _controller: OVTBackEndAdminBundle:SuperAdmin:index }

ovt_back_end_admin_gestion:
    path:     /gestion/{gestion}
    defaults: { _controller: OVTBackEndAdminBundle:SuperAdmin:gestion, gestion:'utilisateur' }
    requirements:
        gestion: utilisateur|client|presta|service

ovt_back_end_admin_gestion_new:
    path:     /gestion/{gestion}/addnew
    defaults: { _controller: OVTBackEndAdminBundle:SuperAdmin:addNew, gestion:'utilisateur' }
    requirements:
        gestion: utilisateur|client|presta|service
        _method:  GET

ovt_back_end_admin_gestion_new_service:
    path:     /gestion/service/addnew
    defaults: { _controller: OVTBackEndAdminBundle:ServiceAdmin:addNew }
    requirements:
        _method:  POST

ovt_back_end_admin_gestion_get_service_by_id:
    path:     /gestion/service/{id}
    defaults: { _controller: OVTBackEndAdminBundle:ServiceAdmin:getServiceById }
    requirements:
        id:  \d+