ovt_general_homepage:
    path:     /
    defaults: { _controller: OVTGeneralBundle:Default:landingPage }

ovt_services_join:
    path:     /session/join
    defaults: { _controller:  OVTGeneralBundle:Default:sessionJoin }
    options:
        expose: true